---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.md"
exclude_paths:
- dist/
- node_modules/
- test/
- coverage/
